import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Box, Container, Flex } from "@chakra-ui/react";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Providers from "./Providers";
import { Session } from "next-auth";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap", // Optional: improves font loading
});

export const metadata: Metadata = {
  title: "AI Powered Blogging Platform",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
  params: Promise<{ session: Session | null }>;
}

export default async function RootLayout({ children, params }: LayoutProps) {
  const resolvedParams = await params;
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        <Providers session={resolvedParams?.session || null}>
          <Flex direction="column" minHeight="100vh">
            <Box
              flex="1"
              pr={{ base: "10px", sm: "10px", md: "10", lg: "20" }}
              pl={{ base: "10px", sm: "10px", md: "10", lg: "20" }}
            >
              <Header />
              <Container padding="0" overflowY="scroll">
                {children}
              </Container>
            </Box>
            <Footer />
          </Flex>
        </Providers>
      </body>
    </html>
  );
}
